### ISSUE TITLE
Use the LPPL

### ISSUE THREAD

**Issue by vermiculus** [thib1235/yLaTeX#1]
Please see qTipTip/TM-style-class#1. I apologize that it is in English and not French – I will try to find a friend to translate it for you better than Google can (assuming you don't already have a working knowledge of English, in which case I applaud you :smile:)

**Comment by thib1235** [comment]
English is fine, no problem! (I apologise for any mistake I could do)
As I said on the qTipTip issue, I was wondering if you knew a licence that forbid commercial use?

**Comment by vermiculus** [comment]
That's the problem: commercial use needs to be allowed to a certain extent. What would not be allowed (as I understand it) is commercial distribution of your source code.

**Comment by thib1235** [comment]
Well, I thought about it, and decided that I would simply use the CC licence...

**Comment by vermiculus** [comment]
Do what you will, but it will never be able to be included in TeX Live :( (and by the terms of the CC license, neither will qTipTip/TM-style-class)

**Comment by thib1235** [comment]
To not be able to be included in TeX live, I agree with you, is a disadvantage but it isn't really likely either... But why couldn't qTipTip's code be included?

Those matters are so complicated! I could switch back to LPPL but I really don't like the idea that someone could use my work to make money!

**Comment by vermiculus** [comment]
compare:

* https://tldrlegal.com/license/latex-project-public-license-v1.3c-(lppl-1.3c)
* https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

**Comment by vermiculus** [comment]
I'd really urge you to reconsider your commercial point, but you can always include an explicit proviso that if the work is to be used to make money, then you must be contacted in writing.

Still, what of the hundreds of thousands of packages that are in use in journal articles, theses, and books? These works are all sold. It's not really the same level of work.

**Comment by thib1235** [comment]
I find the explicit proviso a good idea. But how do you write one? Is it enough to add at the bottom of the README: *For commercial use of this work, please contact me before at thib1235[at]gmail.com*

**Comment by vermiculus** [comment]
Yes, that is enough, but you may wish to cover more bases:

> For commercial use of this Work **or a Derived or Compiled Work** (as defined in the LPPL v1.3c), […]

This would ask folks to contact you if they were going to use your code (or a modification of your code) or a PDF created from your code / modification thereof.

You can also show this message in the log file and terminal output if you wish.

Be aware though that, under the LPPL, someone else may assume maintainership of this work if you fall off the map (the project is dormant AND you cannot be reached for six months). This does not mean that the copyright is transferred to them – just that the new maintainer may make 'official' updates to the project. I've never heard of this happening, though.

I still don't see the point of disallowing commercial use though. Not in this context. It's really the same concept as using Linux on a corporate level. It benefits everyone and makes TeX a more viable option for business *which is important* for community growth. :confused: I've been thinking about this a lot lately and will be writing a short article/RFC about it.

**Comment by thib1235** [comment]
I see that I might have expressed myself wrongly. I did not mean that the package should not be used for corporate or commercial documents (though I'm not sure to find it correct that one sell the document without giving me something). Only that one should not be able to *sell* package based on my work.

But I agree with you, this is a complicated question.

**Comment by vermiculus** [comment]
Be clear: do you wish to restrict selling the package or selling a pdf built with the package?

**Comment by thib1235** [comment]
I want to forbid anyone from selling the package's sources (or derivative work)! And I don't have a clear opinion on selling pdf built with the package

**Comment by ssavinel** [comment]
Hello @HarveySheppard, have you reconsidered the permitted usage of selling pdf built with your package?
This might be the prettiest one I found so far and it would be great to be able to sell books relying on it.

**Comment by HarveySheppard** [comment]
Hey @ssavinel,

Great of you to ask! I actually changed my mind on the whole licensing problem. I now use the MIT license so feel free to use the code as you see fit.

As of now, the license in the repo is changed to MIT!

Out of curiosity and I you want/can, I would love to see the documents that you create with this code!

**Comment by HarveySheppard** [comment]
No more restrictions on commercial work! :tada:

**Comment by ssavinel** [comment]
@HarveySheppard That's great, thank you so much. I'll make sure to send you a copy :)
